name: Mission Intent Guard

on:
  push:
    paths:
      - 'hfo_mission_intent/**/mission_intent*.yml'
      - '!hfo_mission_intent/**/archive/**'
      - '!hfo_mission_intent/mission_intent_template.yml'
  pull_request:
    paths:
      - 'hfo_mission_intent/**/mission_intent*.yml'
      - '!hfo_mission_intent/**/archive/**'
      - '!hfo_mission_intent/mission_intent_template.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (PyYAML)
        run: |
          python -m pip install --upgrade pip
          python -m pip install PyYAML

      - name: Determine changed mission intent files
        id: files
        shell: bash
        run: |
          set -euo pipefail
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git diff --name-only origin/${{ github.base_ref }}...HEAD \
              | grep -E '^hfo_mission_intent/.*/mission_intent.*\.yml$' \
              | grep -v '/archive/' \
              | grep -v 'mission_intent_template.yml' \
              || true
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
              | grep -E '^hfo_mission_intent/.*/mission_intent.*\.yml$' \
              | grep -v '/archive/' \
              | grep -v 'mission_intent_template.yml' \
              || true
          fi > changed_files.txt
          echo "Changed files:" && cat changed_files.txt || true
          CHANGED=$(tr '\n' ' ' < changed_files.txt)
          echo "files=$CHANGED" >> $GITHUB_OUTPUT

      - name: Run mission intent validator (changed files only)
        if: steps.files.outputs.files != ''
        run: |
          python scripts/validators/validate_mission_intents.py ${{ steps.files.outputs.files }}

      - name: No-op when no mission intent files changed
        if: steps.files.outputs.files == ''
        run: echo "No mission intent files changed; skipping guard."
